version: "3.8"

services:
  api_ingestion:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - cctv_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  uploads_data:
    external: true

networks:
  cctv_network:
    external: true
