services:
  # Nama layanan kita
  api_ingestion:
    build: . # Perintahkan Docker untuk membangun dari Dockerfile di folder ini
    ports:
      # Map port 8081 di laptop kita ke port 8081 di dalam kontainer
      - "8081:8081"
    volumes:
      # Ini penting agar file yang diunggah tetap bisa kita lihat dari laptop
      - ./uploads:/app/uploads
    # 'host.docker.internal' adalah alamat khusus untuk terhubung
    # ke layanan yang berjalan di laptop kita (host) dari dalam kontainer Docker.
    extra_hosts:
      - "host.docker.internal:host-gateway"